@Tutorial8_HostAddress = http://localhost:5128

// *** TRIP *** // 
### GET: All trips -> 200 OK
GET {{Tutorial8_HostAddress}}/api/trips
Accept: application/json

### GET: Specific Trip (valid ID) -> 200 OK
GET {{Tutorial8_HostAddress}}/api/trips/1
Accept: application/json

### GET: Specific Trip (invalid ID) -> 404 Not Found
GET {{Tutorial8_HostAddress}}/api/trips/111
Accept: application/json


// *** CLIENT *** //
### GET: All Trips for an existing client -> 200 OK
GET {{Tutorial8_HostAddress}}/api/clients/1/trips
Accept: application/json

### GET: All Trips for non-existing client -> 404 Not Found
GET {{Tutorial8_HostAddress}}/api/clients/111/trips
Accept: application/json

### POST: Create a new client -> 200 OK
POST {{Tutorial8_HostAddress}}/api/clients
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Smith",
  "email": "john.sm@example.com",
  "telephone": "123456789",
  "pesel": "92020413536"
}

### POST: Create a new client (missing required field) -> 400 Bad Request
POST {{Tutorial8_HostAddress}}/api/clients
Content-Type: application/json

{
  "firstName": "",
  "lastName": "Bernardo",
  "email": "invalid",
  "telephone": "123456789",
  "pesel": "123"
}

### PUT: Register client for a trip (valid) -> 200 OK
PUT {{Tutorial8_HostAddress}}/api/clients/1/trips/3
Accept: application/json

### PUT: Already registered -> 409 Conflict
PUT {{Tutorial8_HostAddress}}/api/clients/1/trips/3
Accept: application/json

### PUT: Invalid trip or client -> 404 Not Found 
PUT {{Tutorial8_HostAddress}}/api/clients/111/trips/333
Accept: application/json

### DELETE unregister client from trip (valid) -> 200 OK
DELETE {{Tutorial8_HostAddress}}/api/clients/1/trips/3
Accept: application/json

### DELETE unregister client from trip (not found) -> 404 Not Found
DELETE {{Tutorial8_HostAddress}}/api/clients/1/trips/111
Accept: application/json
